### ISSUE TITLE
[Epic] XMR-BTC: Single Market Maker - Testnet MVP CLI

### ISSUE THREAD

**Issue by D4nte** [comit-network/xmr-btc-swap#129]
By the end of the project:
- [ ] We are running a functioning testnet SP.
- [ ] As a user, we have done successful and aborted swaps against the SP, we are able to recover funds as a user if we abort.
- [ ] We broadcast the SP website address, from which users can find the tools and information to setup the CLI and proceed with a stagenet/testnet swap.

Milestone: https://github.com/comit-network/xmr-btc-swap/milestone/1

**Comment by thomaseizinger** [comment]
Closing because it is an epic from the previous project.
