### ISSUE TITLE
Stagenet Swap

### ISSUE THREAD

**Issue by D4nte** [comit-network/xmr-btc-swap#67]
# Objectives

- Ensure that the software is usable on mainnet without fund loss.
- Learn technical restrictions of the software and protocol.
- Understand whether and what manual recovery tools would be needed by the
user for a MVP.

## Dev Tasks

- [x] Test punishment #54
- [x] Test refund (Implement bob cancel + refund logic) #72 
- [x] Add assertions to check if balances are correct after punish test #72 
- [x] Introduce recursive function to allow test of punish and refund path and facilitate recovery #41
- [x] Poll on the swarm using an event loop #65
- [x] Save states in database and test recovery form said states #56
- [x] Update CLI to pass DB parameters and allow recovery from it #88
- [x] Review CI run to reduce current ~40min execution #69

## Mainnet execution

- [ ] Do a successful swap in mainnet
- [ ] Do a swap in mainnet, restart Alice mid-swap
- [ ] Do a swap in mainnet, restart bob mid-swap

**Comment by D4nte** [comment]
@rishflab @da-kami thoughts on the updated description?

**Comment by thomaseizinger** [comment]
From what I know, we have done multiple successful stagenet swaps now.
